### ISSUE TITLE
Automatically delete unused Swagger.json files when uploading new API Backend Documentation

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#862] opened 2016-02-08 12:14 UTC
@preriasusi mentioned the following (in issue #842):

> It's also not possible to delete Swagger JSON, or edit after upload.

Add a feature to automatically clean up unused or erroneous swagger json files, so that they do not appear in the documentation browser.

**Comment by bajiat** [comment] 2016-05-20 12:10
Closing as duplicate of

**Closed** 2016-05-20 12:15 UTC
Labels: bug, enhancement
