### ISSUE TITLE
Possibility to call APIs without API Key

### ISSUE THREAD

**Issue by preriasusi** [apinf/api-umbrella-dashboard#833] opened 2016-02-02 06:48 UTC
API owners allow direct calls to APIs, and also would like to allow it with Apinf. 

Currently if API calls are made without to Apinf returns an errot of API key missing. 

One idea (Quick fix/hack) would be to to allow API owner to create default API Key (Apinf account), where all the call will be directed if calls come without API Key.

**Comment by brylie** [comment] 2016-05-06 13:04
I marked this as a bug. We have a field on the "Edit API Backend" form to toggle the API Key check, but the changes are not made on API Umbrella. We need to make sure our integration code is passing the updates to all API Backend configuration fields.

**Comment by brylie** [comment] 2016-05-06 13:05
This is also a duplicate of #622

**Comment by bajiat** [comment] 2016-05-20 08:51
Closing as duplicate.

**Closed** 2016-05-20 08:51 UTC
Labels: APIKA, bug, Customer's wish, enhancement
