### ISSUE TITLE
Exception "Sync API Umbrella Users and API Backends" TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by frenchbread** [apinf/api-umbrella-dashboard#1073] opened 2016-06-07 14:22 UTC
Sometimes getting exception while app is running:
```
SyncedCron: Exception "Sync API Umbrella Users and API Backends" TypeError: Cannot read property 'length' of null
    at new ApiUmbrellaError (packages/apinf_api-umbrella/server/apiUmbrellaError.js:23:1)
    at Object.self.adminApi.v1.apiUsers.getUsers (packages/apinf_api-umbrella/server/apiUmbrellaWeb.js:321:1)
    at [object Object].syncApiUmbrellaUsers (server/methods/apiUmbrella.js:9:58)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:1617:18
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Server.apply (packages/ddp-server/livedata_server.js:1616:45)
    at Server.call (packages/ddp-server/livedata_server.js:1559:17)
    at Object.job (server/startup.js:17:16)
    at packages/percolate_synced-cron/synced-cron-server.js:218:1
```

**Comment by brylie** [comment] 2016-06-09 11:35
As the traceback reads, we might have a bug in our API Umbrella getUsers method:

```
Object.self.adminApi.v1.apiUsers.getUsers
(packages/apinf_api-umbrella/server/apiUmbrellaWeb.js:321:1
```

**Comment by brylie** [comment] 2016-06-09 12:25
This is partially resolved by PR #1106. In effect, the problem is related to improper API Umbrella Web configuration settings. 

We can consider whether we need further error checking or work related to this issue.

**Comment by bajiat** [comment] 2016-06-09 13:28
@brylie Can you describe what would be missing after PR #1106 is merged?

**Comment by brylie** [comment] 2016-06-10 07:01
Some thoughts I had were:

- we are not validating the API Umbrella settings, to ensure they point to a valid API Umbrella instance
- we probably do not need the `apiUmbrellaWeb` instance to be globally defined
  - e.g. we can create an instance inside each of the API Umbrella Web methods, that is cleaned up after the method runs
- @frenchbread suggested adding a .updateConfig method to the ApiUmbrellaWeb class,
  - this might not be necessary if we only create/destroy the apiUmbrellaWeb instance from within the Meteor methods

**Closed** 2016-06-10 08:27 UTC
Labels: bug, planning
