### ISSUE TITLE
Improve layout of View API Backend display sections

### ISSUE THREAD

**Issue by brylie** [apinf/api-umbrella-dashboard#834] opened 2016-02-02 10:01 UTC
The "View API Backend" template can use a bit of attention to detail. Specifically, the "Servers" panel can be extended to fill the remaining row columns. Fix the "Servers" layout, and look for any other minor fixes that can be added to the "View API Backend" display tabs.

**Comment by nnn** [comment] 2016-07-08 09:11
Duplicate of #1203

**Closed by nnn** 2016-07-08 09:11 UTC
Labels: duplicate, enhancement
