### ISSUE TITLE
URL matcher fields are misaligned

### ISSUE THREAD

**Issue by saralavanip** [apinf/api-umbrella-dashboard#605] opened 2015-11-10 09:23 UTC
1.Visit https://apinf.io   
2.Sign in   
.3.Select 'API Backends' from menu   
4.Click on 'Add API Backend'   
5.Enter API name   
6.Select the backend protocol from drop down menu   
7.Enter the details of servers: Host and Port   
8.Enter front end host and Backend host   
9.Enter multiple URL matches: Frontend prefix and Backend prefix   
10.Click on 'Submit'  button    

- Added multiple URL matcher fields are misaligned.  

Screenshot:  

![multiple4_url_matchers_notaligned](https://cloud.githubusercontent.com/assets/13309358/11058717/6ed5343a-879d-11e5-89a3-fb4f9c5aec35.png)

**Comment by brylie** [comment] 2015-12-31 12:26
Closing, as duplicate of #522

**Closed** 2015-12-31 12:27 UTC
Labels: duplicate

**Comment by saralavanip** [comment] 2016-01-20 12:37
Verified this resolved issue on latest develop version.
